apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default #by deafult
  source:
    # git repository url
    repoURL: https://github.com/jym272/test-argo.git
    targetRevision: HEAD # always the last commit
    path: k8s/overlay/lab
  destination:
    server: 'https://kubernetes.default.svc' # kubernetes api server
    namespace: default # namespace where the application will be deployed
  syncPolicy:
    automated:
      # can configure a webhook to trigger the sync
      # delete resources that are not defined in the application.yaml
      prune: true
      # undo or overwrite changes made outside of Argo CD
      selfHeal: true # if the application is deleted, recreate it
    syncOptions:
      - CreateNamespace=true # create namespace if it does not exist

